language: csharp
solution: GmailApi/GmailApi.sln
install:
  - nuget restore GmailApi/GmailApi.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release GmailApi/GmailApi.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./GmailApi/UnitTests/bin/Release/UnitTests.dll
