language: csharp
mono: latest
solution: Src/KP.GmailClient.sln

env:
  global:
   - secure: "VKIMVBD/48obdtE5b4CiTDjPd9MWCTCvpOElVTWO3pa6ow/AzJzIUoOisW0wtFdccwy1Bsi/2hI/JVkDiK1RjMT5XkKqCRdtO0IEGTd0JODYhQCcxmSYbg+Kd80pAzcoRUY8czbpP5qRXmECAEAvvJ16cNR13BTBxadfAYP/yfA="

before_install:
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

install:
  - nuget restore Src/KP.GmailClient.sln
  - nuget install xunit.runner.console -Version 2.1.0 -OutputDirectory testrunner

script:
  - xbuild /p:Configuration=Release Src/KP.GmailClient.sln /tv:14.0
  - mono ./testrunner/xunit.runner.console.2.1.0/tools/xunit.console.exe ./Src/KP.GmailClient.Tests/bin/Release/KP.GmailClient.Tests.dll

addons:
  coverity_scan:
    project:
      name: "kpstolk/KP.GmailClient"
      description: "Build submitted via Travis CI"
    #notification_email: me@gmail.com
    build_command_prepend: "msbuild /t:Clean"
    build_command:   "msbuild /t:Rebuild"
    branch_pattern: master
    #branch_pattern: coverity_scan
  srcclr: true
