language: csharp
mono: latest
solution: Src/KP.GmailApi.sln
install:
  - nuget restore Src/KP.GmailApi.sln
  - nuget install xunit.runner.console -Version 2.1.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Src/KP.GmailApi.sln /tv:14.0
  - mono ./testrunner/xunit.runner.console.2.1.0/tools/xunit.console.exe ./Src/KP.GmailApi.Tests/bin/Release/KP.GmailApi.Tests.dll
