language: csharp
solution: GmailApi/GmailApi.sln
install:
  - nuget restore GmailApi/GmailApi.sln
  - nuget install xunit.runners -Version 2.0.0 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release GmailApi/GmailApi.sln
  - mono ./testrunner/xunit.runners.2.0.0/tools/xunit.console.clr4.exe GmailApi/UnitTests/bin/Release/UnitTests.dll
