version: 0.1.{build}

configuration:
- Release
- Debug

platform: Any CPU

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

environment:
  TokenUri: https://accounts.google.com/o/oauth2/token
  PrivateKey:
    secure: onTWKFm3dGo4JA2d4yYxDgkhABAnU2LNfW6I1bMqEheU/UjelDsRGpJErc/qflhIx1edwv6QjeA0mHVop1QsoMV/Fgl40pxboobiSlX8yS3Sd0YpHNHzH218VwtjKZHlNL9+81CEf9JOkSc4kwKwKtEpogD1eadfNuVKUsOcAEgJfrRl+nmpTedxXzA9DmcFn9dYWEYMXGjxsJGslf3INmzO+bCweXPcs2NwlkTllvVWKFx584gW8SuQzv8QAaXUCfumqM08dghNY3AX7zA4AiBLftz+vpRWizq/XOqSOddPGIL7rXffpsL9QKtuU0yZ1/LuSSGExZETx5XQuQXnOM0aIs0MNEnG2ueieTIrBRigc1BsRFtVGjJwbvGZRZFTjgeLVL9xgbZPR1GQhp9eTumDDWzE5C5Ib7N5/s6OZ9bqAXMiTDrvm3hVPmFnrysKzJ3MqyWTQtO4oXqq8vVNo8pDMwebcNAbZN2rH3MbWk5IY/GSUSk0WsOmXAzhVZRbfXWd3L9v8utyMF+/4aatZN4/gPg+KNwQhqyvE0G8g6dzGxNpt53yHUVVOVS6u/5D6XuuJFFAnRChR8D0mLAQOaMt7+qBaYiqQHlyjIQ33B44uoRKF0H0y1gbJh1QePAdOOFuga8QutuENh/9oZNll3E9mATnIIQtEpQq4tNyytBOyldT3NtqJYh0CM3Zo4sAubPJ2/22g5eLxCQOvIkddjVsNATS91O9bGOGrJ3w5hGvbe0E7yxvGdF3CQOGDad0MB88Pb8/VDZ4B2Oqrmntsn8mBg3JL/UMIv/RGlTz3j8vNpDg/5F6sdrjc2ff2iXfQ/XFPc6yHXg0e+Z4RfP6CXvxIIM7YdVm+vswTc6ljpYOwGkcJGhzC25UYaLthJqQspo82a0LzPSWF0eNScTGZnQLycE4sRJvO3IRmcByAqaMsay4x/kfWqPVMcqB2Pviih1QHtbY9Hfn313dPYYnKawtzfmokN2JhkvGZuumGvBABZLPLzjqhSeO9ytMvRtLIhD5MnCpuf2pFVPkTvEa3fUCODpRaOlHHQZO1579VM1QZWIDoGJhwHDDTuO3KvrnA3Iq0iVcMooxs4JbgkPSBSXLsffnCpA2Kbl2arI4Kxpu1mqBnmXDCkQrPnZ70OfchRYkvPTi1cgwGgW8XqbVr0JQ+4/fyRv3HfpRzTSNj6A7xIe8sqgkdkCzObDy0StGt5vzAP2Hh+FmunsWOa+CsUzf6XEpHBhye8x+NupT4KIc3C3EWAZ1q8HC6EHyfLjpxqQ9Dbr1W2o57XjsEslDGqTyIkJYUgCD/WLQ760KCHkbtevYHMtF07/Wn6ad81jSDyVe+mt+FPioL9IQ3lBajZ2T43s53ntj/OS8SCJ5253A4nlPO1iqwlLMUUQUsXwFytrEhzdEqMeM6AVP6RIIo9BiHJWI8peC+RSwBro/etzdUyIKDKltc1XhAXISbqmtG9dggke2TMNeLWWA7RyMdZuKfTJKuVTvSbreG/pSJxZYIpPGXNp8xSlIg8+sA1SzrJeGYtg4Kobpt721BfwPKjWsNKtYIa2woUhVyJDUergnh9q3JzDjT2024qnR1HkIJ3N75JjRVis6aiPHrCsmNgnkX7IpsJLw7sckeJd7KgBhoOWGoscl0vxGO8H03VlPgsWjP6dIjKmhcj48UwACbW/wG2M0rhlXGgS67/d5eSXi5KRzpinNHq1X3oD80ctK6ICuneiWXRnzre9X5i61TpwdFjrYnQeGVWfqom0JDlmtpIRuyGxyiO2Bl5cDb6kiSVuS3wJquX85z6B6Vxdnd5X9lWv6hrbHRwIsv6ouj/JNy+HhrN8oNzyCDYLDDVCF8CJcQshX6SdlnvSNajCGHm1VmrdPQyt33qBv5GTqpRF2t/1OdSPvMNKus0usmK7IdUFviuM8HocmasQY7NVFUx9LVLCf7HBHcrGBm8pqltln3KglyMUPrS8NyEX31M5bcooghlzoXiBSKuBxuZtLTJM2baRM+NyH7XzPoo9P0QM9kQAHZ76hp/kmD3jyH8a/tUIy1/IiBiIzcrfZGNE08oU2uQRBt/tVrjYQiqPjpwNcIZbFMpxMjcm64QG3hhr0Rsw3wnJ4nANzE/6TGVPPHmC/z9lYALyIMyI8ut3Pc7oFk8Ri3tNUlhN03VwlrdRF4OyeDGq+VX+QRpS50B2JiFcUbQXWjoetXysGsy4hkkHnvenMv2+q35tDnKj8jJqPBdaqqyMQDGCoONehj6iFXk+twzJnOpkcWnA6JkDMsMk=
  ClientEmail:
    secure: cNCxTFPHwW+vEpXB9EijRimBOqZ4zd2lWcKm05gmoLIH3rL8fQLurLMZvMPOustRPJB8jtq6u0PYAR1xkq5KowVVDmaYKFZmm/gzsdnS5qk=
  EmailAddress:
    secure: WIxOKY8hKQUwUEJXNDRERvW8x+eXluFU5ofvyScns6U=
  NugetApiKey:
    secure: L7Vp0jAqqqdmHdGulSr+S7Rc6GypRkYhns8GfUDRyBqvUSSUsGGVKy/9b3Er21JJ

before_build:
- nuget restore Src\KP.GmailApi.sln

build:
  parallel: true
  verbosity: normal

deploy_script:
- ps: Build\Build.ps1 -configMode $Env:CONFIGURATION -cloneDir $Env:APPVEYOR_BUILD_FOLDER -nugetApiKey $Env:NugetApiKey
