version: 0.1.{build}

configuration:
- Release
- Debug

platform: Any CPU

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

environment:
  ClientId:
    secure: mX0vgGypLio11EWdGghxCQ6nKfTAM4yp/8aCBMMnPu4I4oeyFlE/OyEZG6KxZcuDnzQjsTuU/zzff3zAlJsghbS5ClIp4R2+SDlKrFBxPmU=
  ClientSecret:
    secure: gjqDtLvNh5T4/p5vQH81q3rU0ABb8K0Lj//qJZbmFpA=
  EmailAddress: me
  RefreshToken:
    secure: ilHENwga6C9p6y8RUFjX+Tl6k0IZxmHc4jgSmTntPh+scHf3bR29JvILKVbeBwq3WKTqX3uuXb2F0/tif/kqGX2yrrHwYLz/fay/kONBpcM=
  NugetApiKey:
    secure: LYPcgM4sbx22im3DfA29YA==

before_build:
- nuget restore Src\KP.GmailApi.sln

build:
  parallel: true
  verbosity: normal

deploy_script:
- Build\Build.ps1 -configMode $Env:CONFIGURATION -cloneDir $Env:APPVEYOR_BUILD_FOLDER -apiKey $Env:NugetApiKey