version: 0.1.{build}

configuration:
- Release
- Debug

platform: Any CPU

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

environment:
  TokenUri: https://accounts.google.com/o/oauth2/token
  PrivateKey:
    secure: onTWKFm3dGo4JA2d4yYxDgkhABAnU2LNfW6I1bMqEhdWBhh5sdDn46LtpUKziCToq405TyIB9kaaj/+dL0wGY8jJ1bnhbx1MQpDKeIXHqehrYezQOsehZden7J0ewGn/v5jIZEebebRSTTkTzGMcsYxqvANj9kjHtgxo4lwhu9zPYPUhbrdgP3u3WPaMGaQ+EiYctOdXBGjo74h1LU6L9NYdOkoK8Xe0qUVGRxE2lcKgJYJZC9lOnpOK802lubXLsSKkzwzEbXd1umhpIybq62CEMWwHu8Yy2VawCGNxBTMjLxixmPzTXU+L9h+HMzsoz6yQNAMUlcs/1ZIuUhdvTPAvU+L3p6mLqHCXi6LURdt5rVtxK1+gzwpx6NDP1aA71L8i1cRq3WQkbmNwLbuNdwWM+QqImCKhImnCfwYe1ltGxxDQLSLSkP8OzYkL2zzRmTULNDSHQ7UgAxt10sYW1AX+oL0OYV2+SPVXmcKj5AcHOSiLubZS9lV63PBLxb1AWieH6fe9ConEAof539h+Wu8mEZ5MYg6hsrA7Zrbe+DMFqUgTNCYROd8s4jm/dpOuhLTr8nh5QHXmxhV3fM7vPRkgt3YkoeXv2rEnRigz2soAkpu+YrNloA6sx14gBQnosCXgMFLbE1PpnoDk6udaOk4YIBofemKWWAwdOiJc7t65sUT1u0QZYmxNwtT0X7voSNh1Ez137MOF7BR9x5Qlz2xCICjQushuNfed2Jty+UETVRkE98o1vF5EyeIpe2d6TTlDCe0Lt3ucB5PYsDiHRczkkZjRqMNBR3WR+g4OZpdU7r/MlxEURT0/ELoL2mPT4iVGmtN+z/Pyl//c2yAxhzdBhUeOQnccP2Fs0Y6ewj192GQbKNHYRyW8pz4AclbZ+yQkg/2fCmwk+hQakdH0uRDTTZHXnhiowtVGkXlpRn3Qp1vFHr3j2SkzDIKbk4L6CIVUni0OL0ZiwvaXQHT8m1V45Xcmz2cAHaDTfiGdVgavjmOeX2CNfeFu/UIYNDViG1xdSVAgMSiKYOXtjWKVg0FiC+PevEj0Ha82ajRPIPYennE2DJeTexwQAxfv2X971chrayiNR21eniCNemwKoqaZrifY5PdZg+P4NLZiF3atFkOakQibLpACkmwCE7N5NAPmGPDlDVXSGiqcmpQirYZYsNZbZ4EswoU9mLPQ+RkcyfrKQoNZMYt1uuPMTU2P3rM4bfFrczubkZtWZ69cD/CZqMLyz5YWe3L2ZN0mgdNRa/92CW77r6ahcoHtSlhLR4A9+d1h/xqxbEx3Z5tT9w0UvXowRQC9Ghtgx+4t5nlsgHfcoU4TmVd7K5PE8ZHKWmpRL5nZd/XOe5VQDpnvzEAiG6rOeZW9PmSE03sluFHP5CusX/fOUqbRkJpgNXPV9+ZVVfphTF/ZqiKFIImoqeqEkjei7olDs+smZnjW2K/ruGVv/kTzLGCrbZ5evSxY73XZ3RU45bwKQ+l7wxJ+pXU9+kcOOvawVhw86gaXgGS2kbr8ZS/UOD5R0mwB+e8/EKIa4lucg2bKRbTxBrdqMAXYr+GnJfScGPVWOqBHhy+P86sKytfPVa/SYuR0InQSbKbuPVFIuSPr3hJHaaQ54o5LbunGVRlHcQydVaIjM+JwyBInbRFQH5mwIsJD9pq23ILUSgCMdIugatLnsHzBcYp/1cRV37I3ljenNAAI0pj2Rvwh8YNMx2gSQWLzB1ArF0TcY5JKaEi1aaRU5HYdLd+tHO1YA7qbwQfPtEyhcmhvj5gwhIIitsNuDbJhA2TK/WQhAWdwKnlz8N6DepZE2svxhAqYwfC8RjXTBTzoJSB6fxlFaV+ifeVyj+xSfXpG3x80hlp9kgB/svgiM8Fs28gxD8lFDjWPRAOcb3QQ3v7LixsIf6i0RHHc6qDVyXMF/lDg9gAgqq8DQIjOLDc9D80WEEI7aAYHPJ8mT3s2vvc5KsKypunzN90eSrj+g9A6iYajaBVHXri9Cwnvs9bCmSpoeW2a1tI4injeq8jT79xbsakO40VNDpZGTCAqVHNs9MtBjbTcqPdJEUi1K3X5kSe/nAV4HNDpMfmphomHRojkp+JVPl3PXhNefq9N4gEpOnAbWtXFd0/u1jXTC5iatSAoTWZ91MzAJo6zZDvwFgYFT5IGr88SSCDfmtptIgkVIsIY0FIVpw7crhaYmrNgNfoBsB7nLueFC4VruZZeZ3vjD5hyHtoIc+rbzU7QcH0ZKevv+N4j/RnOfqaambru9Rf/7lIoGnyjrkb/0ystNyo=
  ClientEmail:
    secure: cNCxTFPHwW+vEpXB9EijRimBOqZ4zd2lWcKm05gmoLIH3rL8fQLurLMZvMPOustRPJB8jtq6u0PYAR1xkq5KowVVDmaYKFZmm/gzsdnS5qk=
  EmailAddress:
    secure: WIxOKY8hKQUwUEJXNDRERvW8x+eXluFU5ofvyScns6U=
  NugetApiKey:
    secure: L7Vp0jAqqqdmHdGulSr+S7Rc6GypRkYhns8GfUDRyBqvUSSUsGGVKy/9b3Er21JJ

before_build:
- nuget restore Src\KP.GmailApi.sln

build:
  parallel: true
  verbosity: normal

deploy_script:
- ps: Build\Build.ps1 -configMode $Env:CONFIGURATION -cloneDir $Env:APPVEYOR_BUILD_FOLDER -nugetApiKey $Env:NugetApiKey
