version: 0.1.{build}

configuration:
- Release
- Debug

platform: Any CPU

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

environment:
  PrivateKey:
    secure: onTWKFm3dGo4JA2d4yYxDgkhABAnU2LNfW6I1bMqEhdWBhh5sdDn46LtpUKziCToq405TyIB9kaaj/+dL0wGYwGWJ0pI6ZmjoE/HHiqQovfXwIizKpq/kZ40GRdfnIosnM5pLqjiEH2G0BQe3qrb6x5t+VmTRcv5OagO/UvF5QDW3/RAKGOvkOdbpQOQ4TnS5uvI9pCAzZSni9YCAA1q/FJMG1oV4PXgy7kMlC9GOiZmq5dudRAqI7yi1qZV0ydSbgP+0h/7LlyEBE+JjkWTrAKfLshevRgmf3ZwytGInzHG9o1wsO18tK3GK0PQnoQv4ALsp5xAbCuic08+NYVn8hpB2/07yokuB2oGZ8kfhmPQG9k+eeczDg63WdLUKcOAYKYadLbn2u1QdszJfvRsFKMhRXXJnVu8gp3MsFRNPTnvxCQG1QkyHn+XJX0dT8A8fFi2MQdrE/jwKTTt+sJlT2B/fJXofZn0HZKW5ehM8H5el/qRg3tRiPFjHtx8xWEMvP+u0MOTZzlmZuAI8OaNm7+ATXRSqQBM1Gv5Tu3Ok4eKjD/0K2vmgefQzlyaf+xQXH6b0EbUWLUgcd4/YsURJbv3FFB9uN80HUVluUveVxRy8PjeUNUiwzQLX+tBF88fbL3fOt/k16GlhC2aBSOZ9/xrTj4PbTgSeNkmgt3QDUo1yXVIfQJoampvg2YCgaUB8YLC654KvHW+nBt2/UCFddCthhjvAQQUwlTAnDttZHnP0ROJRomaXFQA/B3W5nB6YNLO/w1hZMR3ngbgHUw/0iXfxe4E7Bn8TiUsuJZ73nOifoVeA4WQ1EseDQ71aYdCbn1rR3kA6ZINkmWdxxLaSTh0iaXxDeXFsgyrxkyGpwxZ0DWM2Qh0f4jweoDWVd2RVbc34ohyYfEFGapEZyxFFTntEGSGN5mAuAosODx+LwkBeJYaRaY6wyFyT4AjO9U9IiEdPImFhhDcQjItgLhiY0SuYsR9Et4kDzFPRJYSTrYhi92A/7Vi7+0em3Xq6hqgyLNf5dpFUMlswrdRmAVddhFl1d5DdauLQptJmyTRDgFxc6NRQmR/FFF+09SlG+swvuOjUG5hRQDl8xtHMJWeimWZ+BplrROq2N+GEy+ufUd4b43NMeTjZU8hyh2YouLmEX+Gt9MgQf5LhPKFjOkkeYng7i31+rINXeZZxTb7BZecnj6EMUBWVfSJqAmBSUHGRlnGVsLDn4B/aFRzAt5K+MisqysiUhxvMYI3VNcAZU6vX7sjzpGRZ5BD2I2YEB16/OAw2nLA6mEUlfHPzz4xLXgwi8arWTa0i+6Ekj7e2noyPycTHdPk7qRWoM0PIE8/M3H8UcVJ8dqikqm0OEOMFNeJcGO22h+PPQdl0YjP0ukhqafTwl6lAtlW2PTsAIuAo0hHzdZlnmTDKplvHOMhSBj77wM63mKyOzCkYALWEBu+CRxf+pCONqvdPcGifpfuueLq50CIZAl6nbAVwGX269eHibcff5/+qxIBefqLNkugRVyMMSwWtPeeB5pMU95k8L0Yx68e0jwj9iIrtBlZDcIF0DC6x2fVi72ZKiqoEhjCGYt9VWlEJ3KVOJdpEGiuw0JXpj2WMT85/0PX2PXkn8X2UBRC2r+lYnGXQg9VrU7pJe7S05bjatolE9rt2J/pxjumy6P/GLLGObNF05Xd265KYkD/YEI0MqVKF+XQB9erFEA1dVTcvORKRf7ggmbmDaegxp8FFvlz2iSwzxaq6qYPbVEvrUJN9oOA3l52QnPpBNZZytDcS/ji2tDZNK1uCrUq5LJjWJpQpnWuzRy1Z9qiQyT0m34Z0dSKhgsMStEe2U9W8sTc/m96z6RWEsa64yBe9BlExrZ9D0Udg07E1Big5grW4zw0DTHP4C05w+RY+5YFo8Gtg9PWrj7rhg932z0YpFb7J8dxCVwN5qQMMIkKs2c2bUQXp+Txx4qSn0NGCnVA2Gg6OZ4jylE1vB7xYk8SqAFXSFbM2WsDpPJCtgbqGeNs+Kr/d09ov5V1Wo+3SfodhFGt9l6ae2fnTAx28EEJr6K23dsdiG1tklwd+wvcJf/anXPEhKz4QssM8W3+yfQ6Qs2SP6YfDbGa/AXk31OOffBF4WdFykPz6gMObJaLO/8O7quqsnhLnhv24Pv7g9/1sakKR6MhTNGFXK2GZErvz1hUpiASiKj7MuYP55ErbhSixL8uXuA5orduO2t8yHCrZ3dlpEs2tMX8VTazPeyugZHvXQKWIE7eDJoGiVoVTcVZNBt1Fl2ltcZDfn4=
  ClientEmail:
    secure: cNCxTFPHwW+vEpXB9EijRimBOqZ4zd2lWcKm05gmoLIH3rL8fQLurLMZvMPOustRPJB8jtq6u0PYAR1xkq5KowVVDmaYKFZmm/gzsdnS5qk=
  EmailAddress:
    secure: WIxOKY8hKQUwUEJXNDRERvW8x+eXluFU5ofvyScns6U=
  NugetApiKey:
    secure: L7Vp0jAqqqdmHdGulSr+S7Rc6GypRkYhns8GfUDRyBqvUSSUsGGVKy/9b3Er21JJ

before_build:
- nuget restore Src\KP.GmailClient.sln

build:
  parallel: true
  verbosity: normal

deploy_script:
- ps: Build\Build.ps1 -configMode $Env:CONFIGURATION -cloneDir $Env:APPVEYOR_BUILD_FOLDER -nugetApiKey $Env:NugetApiKey
