version: 0.1.{build}

configuration:
- Release
- Debug

platform: Any CPU

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

environment:
  JsonFileContent:
    secure: v27T3On2ma++i6JyDPDMQSN/FtJH1bqns7tQNqj6xmcmDJVqdmIExUo2tzVFNmOpPI6PTIRBsaG36Kb/USRUAMg5jJs5K2rnKeHpkeZfqzggyp6CcNfoE0BV/v7oL2eANVnwB4OxPnzUQ2r7fKDw20JCM6qAjyH3qz0MZjaYxsMCN1EqYnAaHVKYvSHPzfXlk50uvsmixw2Rl/ojC4cnVnrtSRE8P0kctbtH6Uo1GVIkV4QGLlZDe3npoOM2/He4hoJtNdxLvIGOZaPEGSjKrF7JjxA8PdKgsPSUhzSpcXqTgJrSrm5GTZD9vJqUxJ0hvzqjbiihTIoeMMuJwyiptepIAFILFUbkli88MzHxPZPcb47ghxubhosAutouLvPmmitgZ2FaHXiLrARv5YXKH49Gw0hYmc6w3QwO2HNsaFS2ozcF0f2YNGFdfb9AdLKgtnjI7D1zAt3KivriXazCM52lq+68YcIci41nU76q7VaW4TlDskMEmgXWr+52YcgL4YstMPFSYvWQUtDNR/nt3UOaKdXL+nZscHLW+W4RUMt3Lz3xFx2CQ72qO92hOPTZya7lfq+94tpINAdpcGxJLgA7Q0EEQa0vcGEtKnXYV1gRlozsqsZAbA238W9gDuweR6I6LEQ7Hz5bPaoJ3NE/d4ETFkM0lnlgCf1pTo9BeIQCPVyu2DoH9W3gPjbNO1YIDT+cbU181dTrDHOa3KdYt/xxFH8hLlSWTB/xozamLPHBEPiJtowVTvh4vnJYR+NthFG6Fs3HiwFPJBwJHzN+76de2smjPDCnNJ0TfGFTF22FPyQXpr9Igp5Y6zoGH4MgjoyJMFM1awewd8MwdRw/da18ywDzOqHvJ04auRZEe2gikYZi0RTYyVoSbvmOfzfjPwIUU6zrEaYR2Pd6Jo2oiiVO8stmnL5F+LEusAcmjNWHENaxCsfvV6IPLxKEp75F6aXZ8St7PSybRMBpaPfmYM6LtGCrtHz92LW8ciTTBPFZPEg2dkZKDVW/rCOw548hczmMeTAwTxqv2cEK+RJp4Pnb1OLCOkRn9ck+CRzZlfetl5VNxluZBB6pYOiny5rAvy96NX8hXIiA2Th7RTgWCETiFUz5RLLtoUmz8eZr1dP3JPB2O6XsBmCgpLEA4OWVTUodFhyXhaZsnCjrAUydFbpFiF3GKe1PmIntGP/T5Daymk5voGey5JIDs5kNu3gGyZcifaYltaSH9iCyrUqO0GvfqfQAHTzpDYgqAb37qJfcBRMyIrkmYtiM4kJq9zzEz9VOT/O4R0sEYTLZfANZJmSXVnM/QBp3UHxdN23aO/oP3Uab8lL7Vx/XhJzq2b19LDnuDNYDdvhA0QwkpeK/1aE5vrJE1uwbT3wZMyZ1fT2pUBUB6642brIEwMajoPmNofOFNwmsO3yMLD8qFi3f+yD0/2V8VDqhXbNbkiqPNxwRsTh2WD5p5OcX0JXKdPnqdqyZC6OsBF1+PcCw7tijSR5YEiZzwGUURcLrh7KdqwlMcgaT/JL48RKrMLpV+lkDvoK9ecyhOn4pySGWFVVA4MY1YvZnEwdvQ1Gs7TgPMciQl03lGbibFXciABNGG9dDFlTM9bwkGg5RYoy2oUFmXjdiMSVqDFh3XIbNy4N3qsbzqc77X944qrC6zB0eXjdPKc2e5SbDXzo57Nr74l9KpCSD4h3IHcvm4gQNH2DjcBtmaQ5n6P6m7utFjg7D7fIV3e4lG3uoOjP7KqnlTYYM04JB/BTY4Kp6CIuZweaIkMG0PfMsfKiUlKY++sZ+KYOfBhrf893+se+hcrjDCwJ6aG42PMxzDFkVZXen7rpvK0+DeKyOMaSsQJ7bSKtSxZGNcoEdOTI7oIW9dMy5qkwAA6NeI/HwWUsWoTlyn/CSSnLvaHW+S+dd2oG7jS2jOKg6WUIasV9MTgDtFqOHdCqxQ55ukOHZv+W0ljhY7zIHZ3L6nmPxI2uBaUbIhyjtSlV0WvgoLklNpKJbtmz7t7ccCB67WeY1Kz1ngBHpJYWC4qpGKuKG7vXEn+u2uroT4Y83G8L4X6L0FIQVSZZ0Xmnm6nMqgGyLXgpT16l8BT26wNF2vwmCh4hLw5RhOrnXEXrLpXAiDfOpW+cswt1Y4HY56o2o4JsP6nW1CzC9ajYbu53hSOoaSeVdFfgcBjn7k8fwEXQeFP/T8X80q5DiCcPBL1dil17hhet25+d87vFhEoQtLTFn36WP7k3bmbpenCqIlQo1Xkk435RfUOw4vBbT9ORClf+q6BiP36XJbRrjd0Jt1IWRO6Tmt/WEHUfVYBZss0k3A8CYTFgTUCXZ+bESYIzMHnhdAjukjnFFHNKLnqZEjAVn3V3PliSyFKan21as+obOespjFv+9ADGr3BiIR+UwcTQafAo4UYNodlpp+Ssn7LlcfWhHH1m5GKpyaXA4FMN6FuvHWX00blIckgCRHiPTwE77M7Zkl4kpcL0qB1NfC+vRwUpfsDQy9nMUZ+exQX/qSSHVHgPBTEg+S0RdNWBDFgGW3y4IfpLP3YWf2RTpAQw9cUOvXF4cyI9/+btb+nO1aV6J4sDxIGPqrjDsKO2fxX9aiwcjwjbmiymzImuDZ1+QqwKfJUFL7dV2Jx3Z64JtN8cC8cKA7d/k2SsOvOEvYv6LkuOQodYHPvwZ2jlD3u+Vqmle8otH9HR9PrGyy/YNcN5/f+9nrj4DnKAGLcNueRVad7a+S43suzhgWCjd3CW1p9DiyO+AVGF9/JjRF/Zz6Ff/S+zp0IX09Ph+SgKOEJ2nfiKSE5rrpOAVryMm9MdYinAzMRg2iFO2Zq9KFHqAhNHtZsJ+gZcz1UA6GzYmTQLQ1k8yHB9IrpK3A9OJ4NZjpMrWeSQzdinJrXT0Wn103f/isJdpc1319bOaJQCZbE3UoUy26jPiQkhRs6Hm5Mj0u9JqxBtiqoea8jVh9ZFYuaK6wT8IpcXR+IpXVyXOuNDg3Ml1i/ypNxkZwxmWWyrvfVAv03O9TgBNVkC+kF+cSA/4hVXrSdgwY9dkuXvagjCIBQvuS9pZrN+azRbaCLXKnoXphnh/06iUByLzYzQyYKKAWe8BjaqbDvl/ZKXIjQU8UmUOb39thX5BasmTnQN/Mat4YiFUc1JwJd1zrzftrqIFNAKWZaNgJsVsH7N3mIuyoncuVFPT99PCWFc=
  EmailAddress: me
  NugetApiKey:
    secure: L7Vp0jAqqqdmHdGulSr+S7Rc6GypRkYhns8GfUDRyBqvUSSUsGGVKy/9b3Er21JJ

before_build:
- nuget restore Src\KP.GmailApi.sln

build:
  parallel: true
  verbosity: normal

deploy_script:
- ps: Build\Build.ps1 -configMode $Env:CONFIGURATION -cloneDir $Env:APPVEYOR_BUILD_FOLDER -nugetApiKey $Env:NugetApiKey
